### PR TITLE
Enable LVM for rootfs

### PR DESCRIPTION
**Pull request by mdhorn**
The previous solution (#7) enabled the use of LVM for rootfs, but fails if any additional LVMs are used by the Host OS. This was due to all LVMs being activated in the initrd, so they could not be found by the Host OS.

This change disables the logical volume metadata service, and only activates the rootfs logical volume.

### CODE REVIEW

**Comment by mdhorn** [comment]
@josuedhg These changes fix an issue with the previous solution to enable support for using logical volumes for the root partition as well as other partitions (/home, /data, etc)

**Comment by mdhorn** [comment]
@dorileo FYI, found a workable solution.

**Comment by dorileo** [comment]
Nice, @mdhorn I wonder if now we still need the lvm-lvetad service etc.

**Comment by mdhorn** [comment]
> Nice, @mdhorn I wonder if now we still need the lvm-lvetad service etc.

Yes, only because we still need the pvscan service which relies upon it -- even when the lvmetd isn't used.
Otherwise, we'd have to hack up the standard pcscan service file.

**Pull request merged**
